#!/usr/bin/python3

def add_tuple(tuple_a=(), tuple_b=()):
    result = ()
    a = tuple_a[0] + tuple_b[0]
    b = tuple_a[1] + tuple_b[1]
    print(a,b)
    if a < 2 and b < 2: 
        return 0
    if a > 2 and b > 2:
        result = (a,b)
        return result
    print(result)
